import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/Navigation";
import { Inter, Nunito } from 'next/font/google'
import PageWrapper from "./components/PageWrapper";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const nunito = Nunito({ subsets: ['latin'], variable: '--font-nunito' })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${nunito.variable} antialiased`}
      >
        {/* Use Navigation client component */}
        <Navigation />
    <PageWrapper>
  {children}
</PageWrapper>
<Footer/>
      </body>
    </html>
  );
}
