import type { Metadata } from "next";
import "./globals.css";
// import Navigation from "./components/Navigation";
import { Inter, Nunito , Cairo } from 'next/font/google'
import PageWrapper from "./components/PageWrapper";
import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const nunito = Nunito({ subsets: ['latin'], variable: '--font-nunito' })
const cairo = Cairo({
  subsets: ['arabic'],
  weight: ['400', '500', '600', '700'], // الأوزان المطلوبة
  variable: '--font-cairo',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cairo.variable} ${inter.variable} ${nunito.variable} antialiased`}
      >
        {/* Use Navigation client component */}

  {children}

{/* <Footer/> */}
      </body>
    </html>
  );
}
