import type { Metadata } from "next";
import "./globals.css";
// import Navigation from "./components/Navigation";
import { Inter, Nunito , Cairo } from 'next/font/google'
import Navbar from "../components/Navbar";
import FooterWithContact from "../components/Footer";
// import Footer from "./components/Footer";
import { NextIntlClientProvider } from 'next-intl';
import i18nConfig from '../../i18nConfig';
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const nunito = Nunito({ subsets: ['latin'], variable: '--font-nunito' })
const cairo = Cairo({
  subsets: ['arabic'],
  weight: ['400', '500', '600', '700'], // الأوزان المطلوبة
  variable: '--font-cairo',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18nConfig.locales.map((locale: string) => ({ locale }));
}
type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    locale: string;
  };
};
export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = params;

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    console.error(`Could not load messages for locale: ${locale}`, error);
  }

  return (
    <html lang={locale}>
      <body
        className={`${cairo.variable} ${inter.variable} ${nunito.variable} antialiased`}
      >
                <NextIntlClientProvider locale={locale} messages={messages}>

        {/* Use Navigation client component */}
<Navbar/>
  {children}

<FooterWithContact/>
        </NextIntlClientProvider>

      </body>
    </html>
  );
}
